default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  username: root
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>
  pool: 5
  host: db
  protocol: tcp

development:
  <<: *default
  database: <%= ENV['MYSQL_DATABASE'] || 'cev_development' %>

test:
  <<: *default
  database: <%= ENV['MYSQL_TEST_DATABASE'] || 'cev_test' %>

