default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: PlannerPrime
  username: plannerdev
  password: plannerdev
  pool: 5
  socket: /tmp/mysql.sock

#  adapter: mysql2
#  encoding: utf8
#  host: 127.0.0.1
#  pool: 5
#  username: root
#  password: 123456
#  socket: /var/run/mysqld/mysql.sock

development:
  <<: *default
  # database: planner_development

test:
  <<: *default
  database: planner_test

